export const widgetList = ["chat", "clock", "playingTime"];

export const channels = [
  {
    id: "study",
    name: "STUDY SOUND",
    title: "STUDY",
    tags: "#집중력 #편안한",
    img: "/crispsound/images/studythumb.png",
    playList: [
      "s49CT4DTAkw",
      "8IXDbVK138w",
      "1xCfNv6mgWQ",
      "KxwR0kPX3bk",
      "Q-iEfzaikBI",
      "Y3GQUz4HL20",
      "Lp6XlsBm_Lw",
      "hcPXok-Pemg",
      "sVZIMTloWA8",
      "bQzIQa5YKvw",
      "mUeZDu9rBH8",
      "bTJP8RfaCJQ",
      "a_iQqN1Hp74"
    ],
    initialMessages: ["집중력을 높여주는 음악으로 최적의 환경을 만들어 보세요"]
  },
  {
    id: "working",
    name: "노동요",
    title: "WORKING",
    tags: "#돈벌자 #능률상승",
    img: "/crispsound/images/workingthumb.png",
    playList: [
      "TpPwI_Lo0YY",
      "UcnjZfxX5Ss",
      "UHxpi1OIW78",
      "5UlAbfn1Rmo",
      "GdO5z0PIy3I",
      "XdDrv-8ZfwY",
      "W0Iwx_dT_2Q",
      "Atp8GPADPDM",
      "n65JBcDUvW4",
      "74iHoCM83Mg",
      "qgl9ZsT3jKs",
      "4owW9hIbX0o",
      "myWn_g8lkXY",
      "3snaVY5y9Ok",
      "a89vNiNQRvA",
    ],
    initialMessages: ["당신의 노동력이 +10 증가하였습니다", "음악을 듣는 동안 피곤하지 않습니다"]
  },
  {
    id: "animation",
    name: "애니메이션OST",
    title: "ANIMATION",
    tags: "#지브리 #디즈니",
    img: "/crispsound/images/zebri.png",
    playList: [
      "xNTIN58fAP8",
      "wPl0WgWmGao",
      "SpqjvCnnxlQ",
      "WuhKebgRg1w",
      "8CgI0UY6c-I",
      "nmAmNVQbmAE",
      "FK_t6p6C_GM",
      "ikKptNDWkHE",
      "jjn09s3Sh4o",
      "vHgGKcL_GwM",
      "9VPLBCmhCiE",
      "EVyS9UvXkT0"
    ],
    initialMessages: ["감미로운 애니메이션OST"]
  },
  {
    id: "cheerup",
    name: "오늘 하루도 수고했어요",
    title: "CHEER UP",
    tags: "#위로 #격려",
    img: "/crispsound/images/cheerup.png",
    playList: [
      "qdbyV3wVoLY",
      "9Idkwe0FXGQ",
      "Hl3jkH_ySDU",
      "he-akuoohRo",
      "vPs_TBGOA3E",
      "okoeQvOyjTQ",
      "_qmcg4vqmVg",
      "Q8DBnd41dSw",
      "k3xLviSTgYg",
      "8DnV9h-m66Q",
      "3nd640QULCw",
      "cOA2yaGY0GU",
      "ObKI_efcNdw",
      "tPTnvI8qXn4",
      "57x7Rlh-b74",
    ],
    initialMessages: ["오늘 하루도 수고했어요", "당신은 잘하고 있어요"]
  },
  {
    id: "refreshing",
    name: "상쾌하게 기분전환",
    title: "REFRESHING",
    tags: "#시원한 #기분좋은",
    img: "/crispsound/images/refreshing.png",
    playList: [
      "d8pzmY72ucc",
      "a_RWJiGy7Sg",
      "F9Ex1ESEWN4",
      "zrJPDBxk_HA",
      "nUCSfbhiJmw",
      "5EbvFoNY5Y0",
      "cYKEoE8gi88",
      "65nWuTpzh40",
      "OUJhceca_3c",
      "yni45ID2qCc",
      "GdO5z0PIy3I",
      "VLRaD9djoeE",
      "7nr4pe7oQ2E",
      "z9SuJviAOeA",
      "wKjvFRHitVw",
      "gkIxUlJ8bvs",
    ],
    initialMessages: ["기분전환되는 상쾌한 음악"]
  },
  {
    id: "romantic",
    name: "라면먹고 갈래?",
    title: "ROMATIC",
    tags: "#로맨틱 #무드",
    img: "/crispsound/images/romantic.png",
    playList: [
      "5HgU3cN_nds",
      "atkAOjx7kh8",
      "y_7GSNT8xJU",
      "7BFjNrmQO5Y",
      "kALePlJG9tg",
      "uHAI1OazZTI",
      "YdMSN_6If_w",
      "lE8qUAgUQA4",
      "HPosT0cOj9E",
      "pLVK8Md1TOs",
      "hb50T53z8cg",
    ],
    initialMessages: ["오늘 밤을 뜨겁게 만들어줄 음악"]
  },
  {
    id: "cafe",
    name: "CAFE SOUND",
    title: "CAFE",
    tags: "#커피 #재즈",
    img: "/crispsound/images/cafe.png",
    playList: [
      "JHIkAEcQL7o",
      "mGYnJqEphZI",
      "0sHgjMAJTKI",
      "RX8wc7RCXqU",
      "MxWdsVMFm80",
      "r0CQYTOyiPQ",
      "j0QIxs9xNHk",
      "Y_vZmpxL_HY"
    ],
    initialMessages: ["향기로운 커피와 감미로운 음악"]
  },

];
